# Generated by Django 5.0.6 on 2024-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='fee',
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.CharField(default='Your default value here', max_length=500),
        ),
    ]
